import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "@/components";

const lato = Lato({ subsets: ["latin"], weight: ["100", "300", "400"] });

export const metadata: Metadata = {
  title: "Omnifood | Get food fast — not fast food",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="scroll-smooth scroll-pt-12">
      <body className={lato.className}>
        <Header />
        <main className="">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
